### ISSUE TITLE
Figma file link doesnt work

### ISSUE THREAD

**Issue by sshaaf** [PacktPublishing/The-Freelance-Stack-Real-Project-with-NextJS-and-Strapi#1]
the following link was not found 
[Figma Design File](https://www.figma.com/file/N27pbzZuIRUm68cjBKuFxv/Surf-Camp-/-Sharefile?type=design&node-id=0-1&mode=design&t=xfdTWwCpK0fvTjLR-0)

**Comment by Sonakshis** [comment]
Please try this one: 
https://www.figma.com/file/N27pbzZuIRUm68cjBKuFxv/Surf-Camp-%2F-Sharefile?type=design&node-id=0-1&mode=design
