### ISSUE TITLE
missing details to github repo in video course

### ISSUE THREAD

**Issue by sshaaf** [PacktPublishing/The-Freelance-Stack-Real-Project-with-NextJS-and-Strapi#2]
The link to the GitHub repo is not included in the O'Reilly video course. 
https://learning.oreilly.com/videos/the-freelance-stack/9781835465462

**Comment by Sonakshis** [comment]
Hi @sshaaf
The link to the GitHub repository is present under resources. 
![image](https://github.com/PacktPublishing/The-Freelance-Stack-Real-Project-with-NextJS-and-Strapi/assets/85751562/737bf921-2534-4744-b8bd-fd24360af1d2)
